### PR TITLE
93 carousel builder not showing

### LINKED ISSUE #93: Carousel builder not showing
TCE

Description
The carousel build doesn't show up when editing an article (or any other entity). This only happens after you've already open the media attachment window on a given article. Opening the Media manager from the WYSIWYG the first time the page loads works as intended 

Steps to Reproduce
When editing an article:
1. Click the "select media" button on the left hand media attachment section
2. Close the media manager after it opens
3. Open the media manager via the WYSIWYG
4. Select mutliple images 
5. Observe that the carousel builder does not appear

### PR DESCRIPTION
**Pull request by rileymcmaster**
[Staging](https://tce.7.plankdesign.com/admin/articles/72785/edit) - let me know when you are checking this -- I will need to push the right MM build files
[Forecast](https://app.forecast.it/T6464)
Referencing this [TCE issue](https://github.com/plank/canadian-encyclopedia/issues/287)

**The Issue**
When editing an article, if the editor opens the media manager via the WYSIWYG "Image" button then if they select multiple images it will prompt them to create a carousel. If they press a "Select Media" button elsewhere they should not be prompted to create a carousel. 
The bug was that if the editor selects the MM via one of the "Select Media" buttons under one of the side panels such as Featured Image, Tweet Image, etc. then after tried to open the MM via the WYSIWYG they will not ever be prompted to create a carousel. 

**What was done**
The carousel was conditionally being prompted based on a tag prop in the media manager app. 
The "Select Media" buttons on the side panels were storing a tag with that panel's heading (eg. "Interview", "Tweet") but the WYSIWYG was not changing the tag at all. The "Select Media" buttons were being given a data-attribute that was informing the tag prop. I was unable to add the data-attribute to the WYSIWYG button. There was a 'value' prop which the WYSIWYG button had that the other buttons did not. I added a check for that 'value' prop and reset the tag to an empty string if the editor clicks on the WYSIWYG button.

### CODE REVIEW

File: resources/js/components/media-manager.vue [hunk 1]
```diff
@@ -242,6 +248,13 @@ export default {
             this.pageNumber = 1
         }
     },
+    watch: {
+        // everytime user opens MM from a different button - it changes the tag
+        //  we want to reset the selected images
+        tag() {
```
Comment (meganmcewan) [inline resources/js/components/media-manager.vue:254]: this makes sense! thanks for the comments

**Review by meganmcewan — APPROVED** [review]
I don't have a very deep understanding of this code base, but from what i can see this looks good to me. it makes sense and your added comments clarify the changes you've made/
